### ISSUE TITLE
Support digitransit.fi APIs

### ISSUE THREAD

**Issue by tpikonen** [hsarkanen/JollaOpas#11]
It seems (see e.g. here https://github.com/otsaloma/poor-maps/issues/19 ) that reittiopas APIs are not going to be supported for very much longer. JollaOpas should start to use the replacing digitransit.fi APIs.

**Comment by hsarkanen** [comment]
Thanks for noticing. I contacted HSL and their current plan is to stop supporting reittiopas APIs in June. I'll try to find the time to do the update before that.

**Comment by hsarkanen** [comment]
This was already fixed in 36744010d5a200ad2aae4d541cf6ecad292d8ea3, so closing the issue.
