### ISSUE TITLE
No live data in Helsinki

### ISSUE THREAD

**Issue by DagNygren** [hsarkanen/JollaOpas#18]
We have lost live data for the buses in Helsinki. New API again?

**Comment by hsjpekka** [comment]
HSL had technical problems. Live data should be available this week.
https://www.hsl.fi/uutiset/2019/hsln-naytot-ja-reittiopas-ovat-palanneet-reaaliaikaan-16784

**Comment by DagNygren** [comment]
Yes, but their own page already works now which is puzzling.. 
Here: https://vehiclepositionsmapdemo--digitransit.repl.co/

**Comment by DagNygren** [comment]
Talking to the API-providers they say they have changed the contact port:
OLD:
URL Description
mqtts://mqtt.hsl.fi:443/ The bare MQTT protocol with TLS, lightweight.

NEW:
URL Description
mqtts://mqtt.hsl.fi:8883/ The bare MQTT protocol with TLS, lightweight.

So changed from 443 to 8883.
Who is up for an edit of the sources?

**Comment by DagNygren** [comment]
Changed the port from 443 to 8883 by directly editing the file /opt/alien/usr/share/harbour-jollaopas/qml/components/MapElement.qml (line 178) and can confirm it now works again. The new port/server just seems to be very slow compared to the previous one. :-(

**Comment by hsarkanen** [comment]
@DagNygren Thanks for the investigation. I'll build a new package to OpenRepos this evening.

**Comment by Sefriol** [comment]
I made a test run in my version as well and changing ports indeed fixes the problem. I have used it a couple of days now and seems to work fine.

**Comment by hsarkanen** [comment]
This is now fixed in v0.8.2 and the update is available in OpenRepos. I expect that SailfishOS package manager is able to replace the qml source files even if you have done manual modifications but I still recommend to remove your own modifications before upgrading.
