### ISSUE TITLE
Show live map without setting a route

### ISSUE THREAD

**Issue by Emgalai** [hsarkanen/JollaOpas#20]
I would like if it was possible to quickly view the live map (of selected lines) without setting a route.

**Comment by hsarkanen** [comment]
Thanks for the suggestion, but there was similar request earlier [here](https://github.com/hsarkanen/JollaOpas/issues/14#issuecomment-463656833). In addition to [Helsinki Transit Live](https://openrepos.net/content/otsaloma/helsinki-transit-live) in Helsinki and [Busse web site](https://busse.fi/) in Tampere I recommend using [Föli web site](https://live.foli.fi/lemap) in Turku.
