### ISSUE TITLE
Trams are not always shown when using defaults

### ISSUE THREAD

**Issue by ixevix** [hsarkanen/JollaOpas#4]
Hi,
I'm having this weird issue where trams are not always shown.
For example:
I search on my desktop on reittiopas.fi for Hietalahdentori -> Elielinaukio
I get suggested to use tram number 6.
When I do the same search in JollaOpas I get suggested to walk the same route. The bus 65A however is shown.
Time of search 17:50
If I go to settings and switch to least transfers the tram routes are shown normally. It is however very annoying to switch from default to least transfers everytime I want to include trams in my route.
My Change Margin is set to 10 minutes. Every other setting is default. My region is Helsinki.
I used Meegopas on N9 and iirc it had the same issue.

**Comment by mjtorn** [comment]
I've had this as well recently, and I guess now that it's been roughly two years, there's not going to be a fix :/

**Comment by ixevix** [comment]
I've since switched to RouteSkipper which is available from the Jolla Store.
