### ISSUE TITLE
Saisiko kanteen lähtöaika-linja-listan?

### ISSUE THREAD

**Issue by hsjpekka** [hsarkanen/JollaOpas#5]
Muutostoive hyvään oppaaseen. Kun oppaan pienentää, kanteen jää lista matka-ajoista. Minusta parempi olisi lista, jossa näkyy lähtöaika ja ensimmäisen bussin/junan linjanumero. Tietäisin mille pysäkille suuntaisin.

**Comment by hsarkanen** [comment]
Kiitos palautteesta ja hyvästä kehitysideasta!
Lisäsin kanteen aikojen lisäksi nyt linjan numeron enkä poistanut mitään. Pitää jatkossa miettiä jos tuohon lisäisi vaikka liikennevälineen kuvan, mutta toivottavasti tästä on jotain apua.
