### ISSUE TITLE
Scaling in QML

### ISSUE THREAD

**Issue by mjtorn** [hsarkanen/JollaOpas#8]
Hi!

I recently got myself a Fairphone2 and installed (among other apps) JollaOpas to see how everything feels.

There are some issues in rendering and https://sailfishos.org/develop/docs/silica/sailfish-application-scalability.html/ is apparently the fix.

Anything there that you could incorporate in the QML so that other devices would work better?

Thanks!

**Comment by mjtorn** [comment]
There's one _very minor_ caveat on the Fairphone2 with this: there's maybe a bit too much spacing over the favorite routes. I hope this is not a blocker, because it doesn't bother me at least enough to do anything about it for the foreseeable future.

But just in case someone else notices this and/or wants to delve deeper into the world of QML :)

**Comment by hsarkanen** [comment]
The layout has always been a bit hacky so I think very minor caveats are very much acceptable. In my opinion the most important thing is that you can interact with all the UI elements.
